name: bump Version and Tag Repo

run-name: Bump Version and Tag Repo - requested by ${{ github.actor }}

on:
  workflow_dispatch:
    inputs:
      bumpType:
        description: "Type of version bump (major, minor, or patch)"
        required: true
        default: "patch"
        type: choice
        options:
          - major
          - minor
          - patch

jobs:
  call-shared-version-bump-workflow:
    name: Call Shared Version Bump Workflow
    permissions:
      contents: write
    uses: plantemoran-spo/shared-github-workflows/.github/workflows/shared--bump-version-amd-tag--node.yml@v1
    with:
      bumpType: ${{ inputs.bumpType }}
